---
- hosts: localhost
  vars:
    grafana_port: 3001
    loki_port : 3102

  tasks:
  - name: Download Grafana 
    shell : wget https://dl.grafana.com/oss/release/grafana_8.0.3_amd64.deb

  - name : Install Grafana
    command : dpkg -i grafana_8.0.3_amd64.deb
    register :  output

  - debug :
      var : output

  - name : Replace default grafana config
    shell : cat configs/grafana_custom_config.ini > /etc/grafana/grafana.ini

  
  - name : Enable Grafana as a servcie
    command : systemctl enable grafana-server.service

  - name : Start Grafana server 
    command : service grafana-server start

  - name : Download promtail and loki
    shell: wget https://github.com/grafana/loki/releases/download/v2.2.1/promtail-linux-amd64.zip && wget https://github.com/grafana/loki/releases/download/v2.2.1/loki-linux-amd64.zip
    args : 
      chdir : /usr/local/bin
    register : output

  - debug : 
      var : output

  - name : Unzip loki and make it executable
    args : 
      chdir : /usr/local/bin
    shell: unzip loki-linux-amd64.zip && chmod a+x loki-linux-amd64.zip
    args : 
      chdir : /usr/local/bin
    register : output

  - debug : 
      var : output

  - name : Unzip promtails and make it executable
    shell : unzip promtail-linux-amd64.zip && chmod a+x promtail-linux-amd64.zip
    args : 
      chdir : /usr/local/bin
    register : output

  - name : Copy Configurations
    copy : 
      src: ./configs/loki-local-config.yaml 
      dest : /usr/local/bin/loki-local-config.yml 
      
  - copy :
      src : configs/promtail-local-config.yaml
      dest :  /usr/local/bin/promtail-local-config.yml

  - copy : 
      src : ./configs/loki.service
      dest : /etc/systemd/system/loki.service
    
  - copy : 
      src : ./configs/promtail.service
      dest : /etc/systemd/system/promtail.service

  - name : Enable loki and promtail at startup
    shell : systemctl enable loki.service && systemctl enable promtail.service
    register : output
    

  - debug : 
      var :  output

  - name : Start loki and promtails
    shell : service promtail start && service loki start
    register : output
    
  - debug : 
      var :  output

    
  
  
  
  

  




