---
- hosts: localhost
  vars:
    grafana_port: 3001
    loki_port : 3102

  tasks:
  - name: Download grafana binary and extract
    shell: wget https://dl.grafana.com/oss/release/grafana-8.0.3.linux-amd64.tar.gz && tar -zxvf grafana-8.0.3.linux-amd64.tar.gz grafana-8.0.3/
      
  - name : Create files to store logs of shell runs
    shell : mkdir logs && mkdir logs/grafana && mkdir logs/loki && mkdir logs/promtail

  - name : Start grafana server
    shell : cd grafana-8.0.3/bin && ./grafana-server --config=../../configs/grafana_custom_config.ini 2>&1 > ../../logs/grafana/grafana.log &
    register : output

  - debug : 
      var : output

  - name : Download promtail and loki
    shell: wget https://github.com/grafana/loki/releases/download/v2.2.1/promtail-linux-amd64.zip && wget https://github.com/grafana/loki/releases/download/v2.2.1/loki-linux-amd64.zip
    register : output

  - debug : 
      var : output

  - name : Unzip loki and make it executable
    shell: unzip loki-linux-amd64.zip && chmod a+x loki-linux-amd64.zip
    register : output

  - debug : 
      var : output

  - name : Unzip promtails and make it executable
    shell : unzip promtail-linux-amd64.zip && chmod a+x promtail-linux-amd64.zip
    register : output

  - debug : 
      var : output

  - name : Run Loki server
    shell : ./loki-linux-amd64 --config.file=configs/loki-local-config.yaml </dev/null >./logs/loki/loki.logs 2>&1 & sleep 1
    register : output

  - debug : 
      var : output

  - name : Run promtails
    raw : "./promtail-linux-amd64 -config.file=configs/promtail-local-config.yaml </dev/null >./logs/promtail/promtail.logs 2>&1 & sleep 1"
    
    register : output
    

  - debug : 
      var :  output
  
  
  

  




