---
- hosts: localhost
  vars:
    grafana_port: 3001
    loki_port : 3102

  tasks:
  - name: Download grafana binary and extract
    command: wget https://dl.grafana.com/oss/release/grafana-8.0.3.linux-amd64.tar.gz && tar -zxvf grafana-8.0.3.linux-amd64.tar.gz grafana-8.0.3/
  
  - name : Create files to store logs of command runs
    command : mkdir logs && mkdir logs/grafana && mkdir logs/loki && mkdir logs/promtail

  - name : Start grafana server
    command : cd grafana-8.0.3/bin && ./grafana-server --config=../../configs/grafana_custom_config.ini &>./logs/grafana/grafana.log &

  - name : Download promtail and loki
    command: wget https://github.com/grafana/loki/releases/download/v2.2.1/promtail-linux-amd64.zip && wget https://github.com/grafana/loki/releases/download/v2.2.1/loki-linux-amd64.zip

  - name : Unzip loki and make it executable
    command: unzip loki-linux-amd64.zip && chmod a+x loki-linux-amd64.zip
  
  - name : Unzip promtails and make it executable
    command : unzip promtail-linux-amd64.zip && chmod a+x promtail-linux-amd64.zip
  
  - name : Run Loki server
    command : ./loki-linux-amd64 --config.file=configs/loki-local-config.yaml &>./logs/loki/loki.logs &

  - name : Run promtails
    command : ./promtail-linux-amd64 -config.file=configs/promtail-local-config.yaml &>./logs/promtail/promtail.log &

  
  

  





