server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push


scrape_configs:
- job_name:  myapp
  static_configs:
  - targets:
      - localhost
    labels:
      __path__: './logs/*/*logs'
      job: logs2
  pipeline_stages:
  - match:
      selector: '{job="logs2"}'
      stages:
      - regex:
          source: filename
          expression: \/.*\/(?P<service_name>.*)\.logs
      - labels :
          service_name:
     