server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3101/loki/api/v1/push

scrape_configs:
- job_name: mysql
  file_sd_configs:
    - files:
      - ./mysql.yaml
      refresh_interval: 5m
